### PR TITLE
Add Github Actions to build and push consistency check docker images

### LINKED ISSUE #776: Add CI for dmwm/cms_consistency

### PR DESCRIPTION
**Pull request by dynamic-entropy**
Fix https://github.com/dmwm/CMSRucio/issues/776

### CODE REVIEW

**Comment by dynamic-entropy** [comment]
Fix https://github.com/dmwm/CMSRucio/issues/776

**Comment by dynamic-entropy** [comment]
Hello @ericvaandering 
Kindly review. The GitHub `reviewers` section seems disabled for the repo.

Kindly note, 
We will need to add 
`HARBOR_USERNAME` and `HARBOR_TOKEN` in repository secrets.
as well as 
`HARBOR_REPOSITORY` in repository variables.

I have tested the action on my fork here, https://github.com/dynamic-entropy/cms_consistency/actions/runs/8719316952

**Comment by dynamic-entropy** [comment]
@ericvaandering I see that you added yourself as a reviewer; however, I still cannot add/remove a reviewer

**Comment by ericvaandering** [comment]
OK, I will have to review the group permissions in GH.

**Comment by dynamic-entropy** [comment]
Hello @ericvaandering Can you please merge this?
( We can review my merge permission when you get time).

@mrguilima Can you please make your PR (https://github.com/dmwm/CMSRucio/pull/724)  against this repo instead?

**Comment by mrguilima** [comment]
> @mrguilima Can you please make your PR ([dmwm/CMSRucio#724](https://github.com/dmwm/CMSRucio/pull/724)) against this repo instead?

The Dockerfiles from the two repositories are different.  I am applying similar changes from that PR into this repository.

**Pull request merged**
