### PR TITLE
Add scope to quarantined replicas

### LINKED ISSUE #793: Bug: Add `vo=def` when declaring dark files
### Bug Description

`dark-reaper` requires that a `vo` be specified when adding a replica to quarantine. 

This prevents messages from dark-reaper from being sent to open-search.

### Reproduction Steps

Dark Reaper logs
```
Exception 'NoneType' object has no attribute 'vo'
  File \"/usr/local/lib/python3.9/site-packages/rucio/daemons/common.py\", line 215, in _generator
    result = run_once_fnc(heartbeat_handler=heartbeat_handler, activity=activity)
  File \"/usr/local/lib/python3.9/site-packages/rucio/daemons/reaper/dark_reaper.py\", line 166, in run_once
    if replica['scope'].vo != 'def':",
     "error": {"type": "AttributeError", "m essage": "'NoneType' object has no attribute 'vo'", "stack_trace": " 
      File \"/usr/local/lib/python3.9/site-packages/rucio/daemons/common.py\", line 215, in _generator
    result = run_once_fnc(heartbeat_handler=heartbeat_ handler, activity=activity)
  File \"/usr/local/lib/python3.9/site-packages/rucio/daemons/reaper/dark_reaper.py\", line 166, in run_once
    if replica['scope'].vo != 'def':"
```

### Expected Behavior

_No response_

### Possible Solution

- Either make CC add this vo
or 
- Require this requirement from rucio

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by dynamic-entropy**
Fixes https://github.com/dmwm/CMSRucio/issues/793

### CODE REVIEW

**Comment by ericvaandering** [comment]
Can we track down why this is needed? In the past this was not needed. Is there some change?

**Comment by dynamic-entropy** [comment]
@ericvaandering How back in the past? 
This seems to have been added 4 years ago. https://github.com/rcarpa/rucio/commit/c71e8b86c9b6c6a2228539de5f334e0f735a649e

This could have been overlooked by us. It does not affect the functional aspect of things, it only prevents event messages from being logged/added to the topic.

**Comment by ericvaandering** [comment]
So functionally we still don't understand why the dark reaper is not actually deleting anything?

**Comment by dynamic-entropy** [comment]
That we do; we already solved that with the proxy in https://github.com/dmwm/CMSRucio/issues/794
All the `DataBase Exception` errors are gone for the new runs: https://cmsweb.cern.ch/rucioconmon/ce/index

It will not disappear only for the Tape https://github.com/dmwm/CMSRucio/issues/719#issuecomment-2108309670

**Pull request merged**
